version: '3'
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8087:80"
    volumes:
      - ./frontend:/var/www/html
    networks:
      - shield
  backend:
    depends_on:
      - db-shield
    build:
      args:
        user: shield
        uid: 1000
      context: ./backend
      dockerfile: Dockerfile
    image: backend-shield
    container_name: backend-shield
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend/:/var/www/html
    ports:
      - 8007:8000
    networks:
      - shield
  db-shield:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name: db-shield
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: shield
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./backend/.docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - shield
networks:
  shield:
    driver: bridge
